language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: R5wRUxtROqnsr/pDJQf9KjekA+bMB07Iyf/CxkWd1m1BlipHPC24xNqrPL/sFyEeAsBKcyb8v8XO5rIBOIMX9eWMDaiP0ueKM+bh+OnDBbgBVLneKbcFCleV+UrlJBQOo/Zq7D8JZivAqGeeAQQzKUe5achAvI3jAREus5sVPA15jc3p38PjMFLVTdetSqjorjYXvkT6Xk6uP+vnotOYfzsSiZlTwYtDC2L9FXdkJPeS4bFY9usiJvpvnkgFYl/vY6yv2JtXMFzftxGuIVGlzWksC/kOnmrF45ZxdxMs8X6n16tgnfepRy/4rotiPKQjO+D2DKcsJwTp2180O8vutdYWQ7lhUznFiKM9eldvfm6SGM5oZEKq0Vn/fqr21egho6uqQQNzYcVvU+jXODIyLktqGiPLbpY79U4st5XCu6bs/g+HdUxISX9+cHKOlV7Y5R0uIy2vHU0Hb+M0viZfcNAGNdQ13/W5VpbEPBFCEQUsX5fspNKQWX5nkrrHB5LS76zs1UEm24Lp8vTtmUDx6b8Skj4teyggx3yJiwAMjyefiCmffudF5ICpR5DJ0hL2Itsvjsqx1Omjo4dxd138CkxmIVATgXgPhtnAGhrDI1ik5P9NmS5FIvcrY/v/E31945BYJH4sfSLIUZas5fyClkuK78dbfOwRiKzp9WyGUj4=
  app: vast-mesa-75968
