language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: 4CFp7FjnQ7G5h48TCntfah9PPYygVcCgLmoBpAx54KGxyiEQmMc/DUbMKyxbhuvK3ai0pJxtR3RJiT9Fz/GHoJDG+HI9s5sC9iZc6h4t3pyOpa7xkLyVV0cjk40CIppwArdgbHVz0RREkJe9zHS5wa3K6YlqBO7rrd2UWI52maPsjRMXn7IOZ585ahm/ISDPDok3JFny3o54nzuT3CU4Fi3UrAJ7I0m50P4kynwNTMrhHcEWbT3+KI4cFFfDHb4QufvciGvwD1IXq8ys6zIPdt+LORyVabK50kvEM3rjqvXECcMXLIEofgNqUD+xjHHe43yUY8DQs50zzdjnGV3+30T26tL6kewIQNRH8qMIc9fWIqHYzXXjHgZ3sAmIzapNuiC3TWhC7wlAscSxwQnY8FFryRgZvU5SBY6oh0wnMtndvnWJMn+kEr1Wlxr5JKo+3ukJXAV85MN4lRTMhsI3Lv5yDlbJBHsU7fIoVSmxwH88jCR0Rp6wMmzrBTDhxokQ8i/sRu8F9U9r3I2MDemRylGt2PpK1Fm3U1trMQuc6UMtRUdcSgxQuHLcZ5XF1cRiJ/SDegUKPBr7B+VgbcM1qii/IFS8XePzVZmlQ/AMbVVr1srTC6AHICfs4huzki5k6wr1H8E5P9UB1/JPYI3+53sy/IFaYTLRda8qi8/+VsM=
  app: vast-mesa-75968
