language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: psfUd1NC6kcLcAYTozr8KEfbTcrDI7MIZnxET2HKMVGCsNEHiwVLFS+wznuBvN7wqjiX2GPCFzYPWelmvxqdqDNULmn5WCgXY5QPqu0ecP5l2yQVEQmTjaMcfFAjfENdAlfZ36Pj+oXtOGmxMqGi6vOQehBpSOWv+pNJe5eSF8n/g/4M4u7KZcWvAV3nFPeqLpUsvrpcqbaSgo2yVFrtpGq1oy1To70ojZ1duhWt64V0VAkSuZwiYBR5Kky0VQWrfWiZl3Xyu0DNRJBcTJrNOROLjWWUrQy07GGhHgP106vLKBYytPkMEjAS+G/YkVQ90lNzawpcXJOLQvInmVlRtB6gSe8BNQHpBgecRN6IkjdIL8OwsA/suxdYKSlWlo88VNiyK46Ex1KZ3IykRxX4rlgDemldVea6VRJRDB/SpdywLZ0hVfNmwAilL9oF1spz2qwPJM09FNpASeKxmKx8ROiszSBk+D+kGqcOYJ0sxSyMxdp7e1FaY25IftSHSmtV79/gs3IGQIVi1/6pGqsecI5oJ2gDsQKjYo25/f9I3u7EQtRVNnoQBcQM+5n1lynU1+UatwrF6+DuEHZ6Br4hJJKsA4iAX7CP/wTcYvbNpxBAWnxh5CK0qDl86HwZJ0nZZY/nleMJjhjmU9bfUDA69zr2FIIA10s3YYV/5RL0wk8=
  app: vast-mesa-75968
