language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: XQ2Q6UoWfai3hioYzVV+fVtUG79/yX+20lwYOJYAUVLzw4B9i1iHwlxXfQQuP72C+qvjirSmOnPOuYaCgOcVdV7oicGSBfRle6qWqog6eF/nHuKgFy/HFFTq+uzsSCq+S2cxd7mX3EXCWz/H6SdOAY43giF7diTSDhf5JFNlcrEAJktd4xI78Gxkg26njHri5CDUGZm6IehpVX0U6PKe2uC32wfBvQi6rBjA4aBxwkhpJHkFV6tCW9jeDtxIIvY/UlAfmj7E2lR+61zmCoEORPCTYjKFq4n0w+5XBvPb3HF+Oq4pF/fgdJ8Bpe5UiGWSbqHNZsJVXIsxJwjYk/8nHt26ba4hH+Irkre25WgUW15XUNimGfIUs3VL5fNoR1CsEGG6FwcFvMfkR9eFn+ReBaShA8pZgemOhA7T3sb09dIiNqn6Z7s/ivTYByCvSYWvRRWEo5vLzHdcPQcPOT5iZPMctDVtx9+RpcHK92KWzyGq/jxnzsYjxHkYw+GMgtKr5WhVin9fa8mWLdOCZYH1j0ykydMw5VBWqzc8MkmUFG9XIRUrsF7QqqL1OO4+1mRQG8whobYf4f5lFn0Dj9gyCJtLFYDl/B70ZoEbx6HSNviewIgciOeoabrLLMd84uApf+1+iQryRi8fl9eZMe8PZggpxSrr3RoyK7UgUJ09/tU=
  app: vast-mesa-75968
