language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: cb2+n2kTHpkNyI7RWFyrpp1lr2C5v2Ocro+mL5Z78UaiG8rFrKnOUrt/PszaUXGkqBZYBQ03MjSpoGQSs4Pk8626a4gJyohxhHhGPeegLSb0Owo/FCIXty6KuwCYgh6wvNPGzxULooXrfmxwrPdOnFfe6fuQmAVhx66BW4DCGmBJ4Gqgo1/3cpoJjaEuBwkTAMgXBm+5TF8orJb7bKk8HIK0c191WnWH8ziZsUEbLqpw7+cy0VDmfiIUHZ0y1rzprfdctjnBQ7QssBP86va5lKnzKxsCGOT9TFHGhfl6Lnu09U+Yr//QpQ8z/7+WxEtp43l9YAdHNujgq7qQi0Fp+U1PXmAB5Ad5yXrJP04cBmm7r3G8akvviWsjwaO8ToEu+v5FS0R3VqWTGtQen8ydghrlvJlM7xgNmTgonSTbj7bzuce2eLytBn7YgdjnVdWXAmZbsfePk6ViLZtH305U+WWeYRFYTYrj73kvaj6quv3Pr9fjJL7jHOyWdLfVZbZzoKfNcK9x+YbLnOFYwffnFQTof5pS3wkOeGtS+XMSR3P0RYQyWf+VShA1ERkQb9pujoSGlaBl5abHPp/2KFJd80oGaULt0ejT0MXvIc1pDvrrVnbwSdWjrLFnrXt/qcqDN3ZA4uFGVHMT11E5WB+TfIRliqNWFnyMnQflnqdFL/I=
  app: vast-mesa-75968
